apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component
  namespace: sdoyle
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: sampleapp
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-
      labels:
        build.appstudio.openshift.io/application: sampleapp
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: sdoyle
    spec:
      params:
      - name: git-url
        value: https://github.com/maysunfaisal/python-src-docker
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:sdoyle-component-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:0b05a990917f20f82394d02f28841500df23e612
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
